declare const styles: {
	readonly after: string;
	readonly before: string;
	readonly button: string;
	readonly buttonContent: string;
	readonly buttonContentWrapper: string;
	readonly disabled: string;
	readonly l: string;
	readonly linkButton: string;
	readonly m: string;
	readonly noPadding: string;
	readonly outlined: string;
	readonly primary: string;
	readonly round: string;
	readonly s: string;
	readonly secondary: string;
	readonly stretch: string;
	readonly tertiary: string;
	readonly transparent: string;
};
export = styles;
