declare const styles: {
	readonly "grid-col-gap-2xl": string;
	readonly "grid-col-gap-3xl": string;
	readonly "grid-col-gap-4xl": string;
	readonly "grid-col-gap-l": string;
	readonly "grid-col-gap-m": string;
	readonly "grid-col-gap-none": string;
	readonly "grid-col-gap-s": string;
	readonly "grid-col-gap-xl": string;
	readonly "grid-col-gap-xs": string;
	readonly "grid-row-gap-2xl": string;
	readonly "grid-row-gap-3xl": string;
	readonly "grid-row-gap-4xl": string;
	readonly "grid-row-gap-l": string;
	readonly "grid-row-gap-m": string;
	readonly "grid-row-gap-none": string;
	readonly "grid-row-gap-s": string;
	readonly "grid-row-gap-xl": string;
	readonly "grid-row-gap-xs": string;
};
export = styles;
